server.port=8084
spring.application.name=webseries-service
user.service.url=http://localhost:8082
payment.service.url=http://localhost:8085
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=GET
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer