server.port=8081
spring.application.name=auth-service
user.service.url=http://user-service:8082
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=GET
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer